#version: "3"

services:

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # depends_on:
    #   - conzept

  #typesense:
    #image: typesense/typesense:26.0
    #restart: on-failure
    #ports:
    #  - "8108:8108"
    #volumes:
    #  - ./typesense-data:/var/lib/typesense
    #command: '--data-dir /var/lib/typesense --api-key=xyz --enable-cors'

  conzept:
    container_name: conzept
    # env_file:
    #   - .env
    build:
      context: .
    volumes:
      - sslvolume:/etc/ssl
      - ./data/certbot/conf:/etc/letsencrypt/
      - ./data/certbot/www:/var/www/certbot
      # Only use the following  mappings during local development (never commit to main!):
      # Mount the application source for hot-reloading
      - ./app:/var/www/html/app
      # Optionally mount the node_modules directory if needed
      - ./app/explore2/node_modules:/var/www/html/app/explore2/node_modules
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    command: >
      /bin/bash -c "
      cd /var/www/html/app/explore2 && npm i && sh build.sh &&
      cd /var/www/html/app/explore2/libs/lc && sh build.sh"

volumes:
  sslvolume:
  app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./app
    #external: true
